dcweb/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from portal.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('portal.views',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','Home'),
    url(r'^ajax/','AJAXHandle'),
    url(r'^code/','CodeView'),
    #url(r'^djangocodemirror-sample/', include('djangocodemirror.urls'))
    )+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

portal/models.py
from django.db import models

# Create your models here.

portal/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *
# from codemirror2.widgets import CodeMirrorEditor
# from djangocodemirror.fields import CodeMirrorWidget

BANDS = [(1,"Blue"),(2,"Green"),(3,"Red"),(4,"Nir")]

class dataForm(forms.Form):
	year = forms.IntegerField(label="Year")
	layer = forms.ChoiceField(label="Layer",choices = BANDS)
	x1 = forms.CharField(max_length=8,label="x1")
	x2 = forms.CharField(max_length=8,label="x2")
	y1 = forms.CharField(max_length=8,label="y1")
	y2 = forms.CharField(max_length=8,label="y2")

# class CodeForm(forms.Form):
# 	code = forms.CharField(widget=CodeMirrorEditor(options={'mode': 'css'}))	

# class CodeForm2(forms.Form):
# 	code2 = forms.CharField(label="Your content", widget=CodeMirrorWidget(config_name='default'))

portal/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response,render
from django.http import HttpResponseRedirect,Http404,HttpResponse
import json,random
from .forms import *
from django.template import RequestContext

#Datacube Imports
import matplotlib
# Force matplotlib to not use any Xwindows backend.
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import datacube
import pyproj

#Imports for RVI algo
import numpy
from datetime import datetime
from datacube.analytics.analytics_engine import AnalyticsEngine
from datacube.execution.execution_engine import ExecutionEngine
from datacube.analytics.utils.analytics_utils import plot

#Imports for NDVI algo
import xarray as xr
from datacube.api import API
from datacube.ndexpr import NDexpr

#*******************************************************
from django.views.decorators.csrf import csrf_exempt
#*******************************************************

# Create your views here.
@csrf_exempt
def Home(request):
	form = dataForm(request.POST or None)
	imsource = ''
	context = {'imsource':imsource,
				'form':form}
	return render_to_response("five.html",context,context_instance = RequestContext(request))

@csrf_exempt
def AJAXHandle(request):	
	if request.is_ajax():		
		year = int(request.POST['year'])
		layer = request.POST['layer']
		epsg = request.POST['epsg']
		prod = request.POST['prod']
		algo = request.POST['algo']		
		x1 = float(request.POST['x1'])
		x2 = float(request.POST['x2'])
		y1 = float(request.POST['y1'])
		y2 = float(request.POST['y2'])		
		utm44 = pyproj.Proj("+init=EPSG:32644")
		gcs = pyproj.Proj("+init=EPSG:4326")
		x1, y1 = pyproj.transform(gcs, utm44, x1, y1)
		x2, y2 = pyproj.transform(gcs, utm44, x2, y2)
		print x1, x2, y1, y2

		imsource = plot(year,layer,x1,x2,y1,y2,epsg,prod,algo)
		response = {'status': 1, 'message': imsource + "?t=" + str(random.randint(1,1000))} 
	else:
		response = {'status': 0, 'message': "error"} 
	return HttpResponse(json.dumps(response), content_type='application/json')

def plot(year,layer,x1,x2,y1,y2,epsg,prod,algo):	
	if prod == "Reflectance":		
		if algo == "None":	
			return Reflectance(x1,x2,y1,y2,year,layer)		
		elif algo == 'RVI' or algo == 'TVI' or algo == 'NDVI':
			return algos(x1,x2,y1,y2,year,algo)
		else:
			return ''
	elif prod == "NDVI":
		return NDVI(x1, x2, y1, y2, year)
	elif prod == "LST":
		return LST(x1, x2, y1, y2, year)


def Reflectance(x1, x2, y1, y2, year,layer):
	dc = datacube.Datacube(config="/home/sharat910/.datacube.conf")
	la = dc.load(product=get_reflectance_product(year), x=(x1, x2), y=(y1,y2))
	print la
	if layer == "1":
		a = la.blue
	elif layer == "2":
		a = la.green		
	elif layer == "3":
		a = la.red
	elif layer == "4":
		a = la.nir
	a = a.where(a != a.attrs['nodata'])
	print str(year)
	a = a.where(a<1)
	a = a.loc[str(year)]
	lay = get_right_layer(a)
	lay.plot()
	path = 'media/images/' +  str(year) +  '.png'
	plt.savefig(path)
	plt.clf()
	return path

def NDVI(x1, x2, y1, y2, year):	
	dc = datacube.Datacube(config="/home/rishabh/.datacube.conf")
	la = dc.load(product=get_NDVI_product(year), x = (x1, x2),y = (y1, y2))
	a = la.NDVI.loc[str(year)]
	a = a.where(a != a.attrs['nodata'])
	a = a.where(a < 1)
	a = a.where(a > -1)
	lay = get_right_layer(a)
	lay.plot()
	path = 'media/images/' + 'prod-ndvi' + str(year) + '.png'
	plt.savefig(path)
	plt.clf()
	return path

def LST(x1, x2, y1, y2, year):
	dc = datacube.Datacube(config="/home/rishabh/.datacube.conf")
	la = dc.load(product=get_LST_product(year), x = (x1, x2),y = (y1, y2))
	a = la.LST.loc[str(year)]
	a = a.where(a != a.attrs['nodata'])
	a = a.where(a > 220)
	lay = get_right_layer(a)
	lay.plot()
	path = 'media/images/' + 'prod-lst' + str(year) + '.png'
	plt.savefig(path)
	plt.clf()
	return path

def algos (x1, x2, y1, y2, year,algo):
	dc = datacube.Datacube(config="/home/rishabh/.datacube.conf")	
	
	a = AnalyticsEngine()	
	e = ExecutionEngine()

	product = get_reflectance_product(year)
	#assert product
	#dc.list_products() is pandas dataframe, .loc[:]['name'] selects
	#   the products is a pandas series. values is array
	assert (product in dc.list_products().loc[:]['name'].values), "Product not in database"

	# 2 index for platform, 3 for product type
	for prod  in dc.list_products().loc[:].values:
	    if(product == prod[0]):
	        platform = prod[2]
	        product_type = prod[3]

	
	# assert time
	la = dc.load(product=product, x = (x1, x2),y = (y1, y2))
	# this is date of product (la.items()[0])[1].values[0]
	date_of_prod = (la.items()[0])[1].values[0]
	#this is numpy.datetime64

	# TO DO COMPARE numpy.datetime64 with datetime.datetime    
	#assert (date_of_prod >= time1 and date_of_prod <= time2), "Product not in the provided time"

	time1 = datetime(year, 1, 1)
	time2 = datetime(year, 12, 31)
	# calculate output
	dimensions = {'x':    {'range': (x1, x2)},
	              'y':    {'range': (y1, y2)},
	              'time': {'range': (time1, time2)}}

	# create arrays
	b40 = a.create_array((platform, product_type), ['nir'], dimensions, 'b40')
	b30 = a.create_array((platform, product_type), ['red'], dimensions, 'b30')

	if algo == 'RVI':
		#ratio vegetation index
		rvi = a.apply_expression([b40, b30], '(array1 / array2)', 'rvi')

		e.execute_plan(a.plan)

		#result x array
		res = e.cache['rvi']['array_result']['rvi']
		lay = get_right_layer(res)
		lay.plot()
		
		path = 'media/images/' +  'rvi-' + str(year) + '.png'
	elif algo == 'NDVI':
		ndvi = a.apply_expression([b40, b30], '((array1 - array2) / (array1 + array2))', 'ndvi')

		e.execute_plan(a.plan)

		#result x array
		res = e.cache['ndvi']['array_result']['ndvi']
		lay = get_right_layer(res)
		lay.plot()
		path = 'media/images/' +  'ndvi-' + str(year) + '.png'

	elif algo == 'TVI':
		#Transformed Vegetation Index
		tvi = a.apply_expression([b40, b30], '(sqrt(((array1 - array2) / (array1 + array2)) + 0.5) * 100)', 'tvi')

		e.execute_plan(a.plan)

		#result x array
		res = e.cache['tvi']['array_result']['tvi']
		lay = get_right_layer(res)
		lay.plot()
		path = 'media/images/' +  'tvi-' + str(year) + '.png'
	else:
		pass 	
	plt.savefig(path)
	plt.clf()
	return path

def get_right_layer(array):
	import numpy as np
	for i in range(len(array)):
		arr = array[i]
		if not np.allclose(arr.where(arr == 0.0),arr):
			return arr
	return None

def get_reflectance_product(year):	
	if year<=1995 or year == 2010:
		product = 'ls5_ledaps_albers'
	elif year<=2003:
		product = 'ls7_ledaps_albers'
	elif year == 2015:
		product = 'ls8_ledaps_albers'
	return product

def get_NDVI_product(year):	
	if year<=1995 or year == 2010:
		product = 'Output_NDVI'
	elif year<=2003:
		product = 'Output_NDVI_le7'
	elif year == 2015:
		product = 'Output_NDVI_lc8'
	return product

def get_LST_product(year):	
	if year<=1995 or year == 2010:
		product = 'Output_LST'
	elif year<=2003:
		product = 'Output_LST_le7'
	elif year == 2015:
		product = 'Output_LST_lc8'
	return product

def get_sat(year):
	if year<=1995 or year == 2010:
		satellite = 'LANDSAT_5'
	elif year<=2003:
		satellite = 'LANDSAT_7'
	elif year == 2015:
		satellite = 'LANDSAT_8'
	return satellite

def CodeView(request):
	form = CodeForm2(request.POST or None)
	context = {'form':form}
	return render_to_response("code.html",context,context_instance = RequestContext(request))

portal/templates/UI/one.html
<!DOCTYPE html>
<html>
<head>
	<style>
		#id_submit{
			text-align:center;	
		}
		img#id_isro{
			float:left;
			padding-left: 20px;
			margin-top:0;
			height:85px;
		}
		img#id_iirs{
			float:right;
			padding-right: 20px;
			margin-top:0;
			width:80px;
		}
		img#space{
			float:right;
			padding-right: 20px;
			margin-top:0;
			height:500px;
			width:500px;
		}
		h2{
		  font-size:35px;
		  text-align:center;
		  font-family:Times New Roman;
		  max-width:1250px;	
		}	
		div#div1{
			border-style:solid;
			max-width:600px;
			padding-bottom:10px;
			padding:20px;
		}
	</style>
</head>
<body>
	<h2><img src="isro.jpg" id="id_isro" ></img><u>Satellite Data Cube<img src="iirs.jpg" id="id_iirs"></img><br/><br/></u></h2>
	<p id="demo"></p>
	<p id="demo2"></p>
	<img id="space" src="space-008.jpg" height=350px width=400px></img>
	
<div id="div1">	
		<label for="id_x1">x1:</label> <input id="id_x1" maxlength="8" name="x1" type="number" value="79.0" step="0.01" required />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	   Year :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 		 <input type="range" id="input_year" min="1990" max="2015" step="5" value="1990" style="width:150px" oninput="showValue(this)">
  		 <output id="result" for="input_year">1990</output><br/><br/>
		<label for="id_x2">x2:</label> <input id="id_x2" maxlength="8" name="x2" type="number" value="79.05" step="0.01" required/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Layer no. :
  		<input type="range" id="input_layer" min="1" max="4" step="1" value="1" style="width:100px" oninput="showValue(this)">
 	    <output id="result2" for="input_layer">1</output><br/><br/>
		<label for="id_y1">y1:</label> <input id="id_y1" maxlength="8" name="y1" type="number" value="30" step="0.01" required/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Product :&nbsp;&nbsp;&nbsp;&nbsp;
		<select id="product" onchange="showValue(this)">
			<option value="Reflectance">Reflectance</output>
			<option value="NDVI">NDVI</output>
			<option value="LST">LST</output>
		</select><br/><br/>
		<label for="id_y2">y2:</label> <input id="id_y2" maxlength="8" name="y2" type="number" value="30.05" step="0.01" required/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		EPSG:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="number"  id="id_epsg" value="32644"/>
		
	<div id="id_submit">
		<br/><button type="submit" id="id_submit" onclick=funct() value="Submit">Submit</button></div>
</div>
	<script>
		document.getElementById("input_year").value = 1990;
		document.getElementById("input_layer").value = 1;
		document.getElementById("product").value = "Reflectance";
		document.getElementById("id_epsg").value = 32644;
		document.getElementById("id_x1").value = 79.0;
		document.getElementById("id_x2").value = 79.05;
		document.getElementById("id_y1").value = 30;
		document.getElementById("id_y2").value = 30.05;
		var year=1990, layer=1, prod="Reflectance", x1, x2, y1, y2;
		function showValue(obj){
			if (obj.id=="input_year") {
			document.getElementById("result").innerHTML=obj.value;
			 year=obj.value;
			}
			if (obj.id=="input_layer") {
			document.getElementById("result2").innerHTML=obj.value;
			 layer=obj.value;
			}
			if (obj.id=="product") {
			 prod=obj.value;
			}
			
		}
		function funct(){
			x1=document.getElementById("id_x1").value;
			x2=document.getElementById("id_x2").value;
			y1=document.getElementById("id_y1").value;
			y2=document.getElementById("id_y2").value;
			year=document.getElementById("input_year").value;
			layer=document.getElementById("input_layer").value;
			prod=document.getElementById("product").value;
			if(x1==null||x1==""||x2==null||x2==""||y1==null||y1==""||y2==null||y2=="")
				alert("Please fill missing fields!");
			
		}
	</script>
	
</body>
</html>

portal/templates/UI/try.html
<!DOCTYPE html>
<html>
<body>

<p id="demo">Let AJAX change this text.</p>

<button type="button"
onclick="loadDoc('new', myFunction)">Change Content
</button>

<script>
function loadDoc(url, cfunc) {
  var xhttp;
  xhttp=new XMLHttpRequest();
  xhttp.onreadystatechange = function() {
    if (xhttp.readyState == 4 && xhttp.status == 200) {
      cfunc(xhttp);
    }
  };
  xhttp.open("GET", url, true);
  xhttp.send();
}

function myFunction(xhttp) {
  document.getElementById("demo").innerHTML = xhttp.responseText;
}
</script>
</body>
</html>


h3 {
			background-image:url("space-008.jpg");
			color:white;
			text-align:center;
			font-size:25px;
		}
body{
			 background-image: url("images.jpg");
			background-repeat: repeat-x;
		}

function showValue(obj){
			if (obj.id=="input_year") {
			document.getElementById("result").innerHTML=obj.value;
			 year=obj.value;
			}
			if (obj.id=="input_layer") {
			document.getElementById("result2").innerHTML=obj.value;
			 layer=obj.value;
			}
			if (obj.id=="product") {
			 prod=obj.value;
			}
			document.getElementById("demo").innerHTML=year+" "+layer+" "+prod;
		}

document.getElementById("demo").innerHTML=year+" "+layer+" "+prod;

portal/templates/code.html
{% extends "djangocodemirror/sample_base.html" %}
{% load djangocodemirror_assets %}

{% block djangocodemirror_assets_loading %}
{% djangocodemirror_get_bundles form.content %}
{% endblock %}

portal/templates/five.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<!-- <link rel="icon" href="media/images/isro.png" type="image/png" sizes="16x16"> -->
	<link rel="shortcut icon" type="image/x-icon" href="media/images/favicon.ico"/>
	<title>Satellite DataCube</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/look.css' %}">
	<script   src="https://code.jquery.com/jquery-3.0.0.min.js"   integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0="   crossorigin="anonymous">	</script>
</head>
<body>
	<h2><img src="media/images/isro.jpg" id="id_isro" ></img><u>Satellite Data Cube<img src="media/images/iirs.jpg" id="id_iirs"></img><br/><br/></u></h2>	
	<img id="image_data" src="{{imsource}}"></img>
	<div id="map"></div>
	<div id="div1">	
		
	    Year :&nbsp;&nbsp;&nbsp;
 		 <input type="range" id="input_year" min="1985" max="2015" step="5" value="1995" style="width:150px" oninput="showValue(this)">&nbsp;
	     <output id="result" for="input_year">1995</output>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		
	    Layer no. :&nbsp;&nbsp;&nbsp;
  		<input type="range" id="input_layer" min="1" max="4" step="1" value="1" style="width:100px" oninput="showValue(this)">&nbsp;&nbsp;
	    <output id="result2" for="input_layer">1</output>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		
	    Product :&nbsp;&nbsp;
		<select id="product" onchange="showValue(this)">
			<option value="Reflectance">Reflectance</output>
			<option value="NDVI">NDVI</output>
			<option value="LST">LST</output>
		</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		
		Algos :&nbsp;&nbsp;
		<select id="algo" onchange="showValue(this)">
			<option value="None">None</output>
			<option value="NDVI">NDVI</output>
			<option value="RVI">RVI</output>
			<option value="TVI">TVI</output>
		</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		
		<button type="submit" id="id_submit2" onclick=funct() value="Submit">Submit</button>
		
		<br/><br/>
		<label for="id_x1">x1:</label> <input id="id_x1" maxlength="8" name="x1" size="5" type="number" value="79.0" step="0.01" required />
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    <label for="id_x2">x2:</label> <input id="id_x2" maxlength="8" name="x2" type="number" value="79.05" step="0.01" required/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<label for="id_y1">y1:</label> <input id="id_y1" maxlength="8" name="y1" type="number" value="30" step="0.01" required/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<label for="id_y2">y2:</label> <input id="id_y2" maxlength="8" name="y2" type="number" value="30.05" step="0.01" required/>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		EPSG:&nbsp;&nbsp;&nbsp;
		<input type="number"  id="id_epsg" value="32644"/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		
		<button type="submit" id="ipython" onclick="window.open('http://localhost:8888/tree/examples/notebooks')" target="_blank">iPython instance</button>
	</div>
	<script type="text/javascript">
		var csrf_token = {{csrf_token}};
	</script>		
	<script src="{% static 'javascript/webscript.js' %}"></script>
	<script async defer
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkKOjbHoyazntRDSRSrdFuxvjxFu8G0HU&callback=initMap">		
    </script>
</body>
</html>

portal/templates/one.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<style>
		#id_submit{
			text-align:center;	
		}
		img#id_isro{
			float:left;
			padding-left: 2.5%;
			margin-top:0;
			height:85px;
		}
		img#id_iirs{
			float:right;
			padding-right: 2.5%;
			margin-top:0;
			width:80px;
		}
		img#image_data{
			float:right;
			padding-right: 20px;
			margin-top:0;
			height:35%;
			width:45%;
		}
		h2{
		  font-size:35px;
		  text-align:center;
		  font-family:Times New Roman;
		  max-width:1950px;	
		}	
		div#div1{
			border-style:solid;
			max-width:35%;
			padding-bottom:10px;
			padding:20px;
			margin-left:5%;
		}
		input[type="number"] {
   			width:17%;
		}
	</style>
	<script   src="https://code.jquery.com/jquery-3.0.0.min.js"   integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0="   crossorigin="anonymous"></script>
</head>
<body>
	<h2><img src="media/images/isro.jpg" id="id_isro" ></img><u>Satellite Data Cube<img src="media/images/iirs.jpg" id="id_iirs"></img><br/><br/></u></h2>
	<p id="demo"></p>
	<p id="demo2"></p>
	<img id="image_data" src="{{imsource}}"></img>
	
<div id="div1">	
		<label for="id_x1">x1:</label> <input id="id_x1" maxlength="8" name="x1" type="number" value="79.0" step="0.01" required />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	   Year :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 		 <input type="range" id="input_year" min="1990" max="2015" step="5" value="1990" style="width:150px" oninput="showValue(this)" list="ticks1">
  		 <datalist id="ticks1">
			<option>1990</option>
			<option>1995</option>
			<option>2000</option>
			<option>2005</option>
			<option>2010</option>
			<option>2015</option>
		</datalist>
	     <output id="result" for="input_year">1990</output><br/><br/>
		<label for="id_x2">x2:</label> <input id="id_x2" maxlength="8" name="x2" type="number" value="79.05" step="0.01" required/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Layer no. :
  		<input type="range" id="input_layer" min="1" max="4" step="1" value="1" style="width:100px" oninput="showValue(this)" list="ticks2">
 	     <datalist id="ticks2">
			<option>1</option>
			<option>2</option>
			<option>3</option>
			<option>4</option>
		</datalist>
	    <output id="result2" for="input_layer">1</output><br/><br/>
		<label for="id_y1">y1:</label> <input id="id_y1" maxlength="8" name="y1" type="number" value="30" step="0.01" required/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Product :&nbsp;&nbsp;&nbsp;&nbsp;
		<select id="product" onchange="showValue(this)">
			<option value="Reflectance">Reflectance</output>
			<option value="NDVI">NDVI</output>
			<option value="LST">LST</output>
		</select><br/><br/>
		<label for="id_y2">y2:</label> <input id="id_y2" maxlength="8" name="y2" type="number" value="30.05" step="0.01" required/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		EPSG:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<input type="number"  id="id_epsg" value="32644"/>
		
	<div id="id_submit">
		<br/><button type="submit" id="id_submit" onclick=funct() value="Submit">Submit</button></div>
</div>
	<script>
		document.getElementById("input_year").value = 1990;
		document.getElementById("input_layer").value = 1;
		document.getElementById("product").value = "Reflectance";
		document.getElementById("id_epsg").value = 32644;
		document.getElementById("id_x1").value = 79.0;
		document.getElementById("id_x2").value = 79.05;
		document.getElementById("id_y1").value = 30;
		document.getElementById("id_y2").value = 30.05;
		var year=1990, layer=1, prod="Reflectance", x1, x2, y1, y2,epsg;
		function showValue(obj){
			if (obj.id=="input_year") {
			document.getElementById("result").innerHTML=obj.value;
			 year=obj.value;
			}
			if (obj.id=="input_layer") {
			document.getElementById("result2").innerHTML=obj.value;
			 layer=obj.value;
			}
			if (obj.id=="product") {
			 prod=obj.value;
			}
			
		}

		function funct(){
			x1=document.getElementById("id_x1").value;
			x2=document.getElementById("id_x2").value;
			y1=document.getElementById("id_y1").value;
			y2=document.getElementById("id_y2").value;
			year=document.getElementById("input_year").value;
			layer=document.getElementById("input_layer").value;
			prod=document.getElementById("product").value;
			epsg = document.getElementById("id_epsg").value;
			if(x1==null||x1==""||x2==null||x2==""||y1==null||y1==""||y2==null||y2=="")
				alert("Please fill missing fields!");
			console.log("Here")
			$.ajax({
			type: "POST",
			url: "/ajax/",
			dataType: "json",
			async: true,
			data: {
				csrfmiddlewaretoken: '{{csrf_token}}',
				x1:x1,
				x2:x2,
				y1:y1,
				y2:y2,
				year:year,
				layer:layer,
				prod:prod,
				epsg:epsg,
			},
			success: function(data) {
				if(data.status == 1){
					document.getElementById("image_data").src = data.message;
				}    			
			}	
			
			});
}
	</script>
	
</body>
</html>